name: Build and SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with OpenJDK 21.0.5 and Run SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures full commit history for SonarQube analysis

      - name: Set up JDK 21.0.5 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.5'

      - name: Verify Java Version
        run: java -version

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew
        working-directory: src/adservice

      - name: Download Gradle Repositories
        run: ./gradlew downloadRepos
        working-directory: src/adservice

      - name: Install Application Distribution
        run: ./gradlew installDist
        working-directory: src/adservice

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          projectBaseDir: src/adservice
          args: >
            -Dsonar.sources=src
            -Dsonar.java.binaries=build/install/hipstershop/lib

      # Uncomment if you want to fail the build if the Quality Gate fails
      # - name: SonarQube Quality Gate Check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
